### ISSUE TITLE
Not able to Extract SHA256 PCR Bank Values 

### ISSUE THREAD

**Issue by Deepansharora27** [google/go-tpm-tools#297]
Hi 
I was testing out go-tpm-tools and ran into an issue which I think is worth highlighting. 
I was trying to read all the PCR's for the Hash Algorithm SHA256. 

Here is where I faced the following issues: 
1).When I build the code and execute `sudo ./gotpm read pcr`, it by default provides me with the SHA1 Bank values. But I didn't wanted this and instead wanted to have PCR Values listed for SHA256. In the `--help` interface of the CLI, I was not able to see any flag by default for setting the Hash Algorithm as SHA256. 
So with this, I came across the code [here](https://github.com/google/go-tpm-tools/blob/master/cmd/read.go) and saw that, there is this `--hash-algo` flag which let's us set the Hash Algorithm as SHA256 and when I set this in the CLI, it just returned me the Empty String `SHA256:` like this and did not print out the PCR Values. 

2).As a next step to this, I hard coded the `pcrHashAlgo `value as `tpm2.AlgSHA256` [here](https://github.com/google/go-tpm-tools/blob/master/cmd/read.go#L21) but still it only returned me the Blank String `SHA256:` and did not return me the PCR Values 

Why is this happening is something I am curious about ? Any help will be appreciated on this 
Thanks !!

**Comment by chrisfenner** [comment]
Hi Deepanshu,

Your TPM has only the SHA1 bank enabled, so it can only return SHA1 PCR values.

**Comment by Deepansharora27** [comment]
Hi Chris 
Is there a way though which we can enable other Banks ?

**Comment by chrisfenner** [comment]
Yes but not through go-tpm-tools; only the system BIOS can do that. If it's configurable on your system, it's probably buried in your BIOS settings screen.

I [believe](https://github.com/google/go-tpm-tools/blob/5dd1056853aa7354ae1d3522dacab25e1dd09384/cmd/read.go#L30) that `gotpm read pcr` will give you all the currently active PCRs on the system, so you can use that to check your configuration. But unfortunately, it is not possible (by design of TPM) to enable banks on a physical TPM using go-tpm.

**Comment by Deepansharora27** [comment]
Interesting !! Thanks for helping out Chris
